title: Mathieu Fick # your name (or website title) here
logo: "/images/true grit mask.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Undegraduate Senior of Geography and Environmental Systems</strong> at University of Maryland, Baltimore County. 
  <br><br>
  <strong>Focus:</strong> Planetary GeoScience and Atmospheric Systems 
  <br><br> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
